/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.controllers.user;

import com.mycompany.db;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author PC
 */
public class quanlygiaodich extends javax.swing.JInternalFrame {

    /**
     * Creates new form quanlygiaodich
     */
    public quanlygiaodich() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbnganhang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnchuyennhanh = new javax.swing.JRadioButton();
        btnchuyenthuong = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtsotk = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txttien = new javax.swing.JTextField();
        btnluu = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btntimkiem = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtloinhan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhsach = new javax.swing.JTable();
        btnXuatExcel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(640, 550));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Ngân hàng thụ hưởng:");

        cbnganhang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vietcombank (Ngân hàng TMCP Ngoại Thương Việt Nam)", "BIDV (Ngân hàng Đầu tư và phát triển Việt Nam)", "Techcombank (Ngân hàng Kỹ thương Việt Nam)", "TP Bank (Ngân hàng tiên phong)", "MB Bank (Ngân hàng Quân đội Việt Nam)" }));
        cbnganhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnganhangActionPerformed(evt);
            }
        });

        jLabel5.setText("Loại phương thức chuyển tiền:");

        btnchuyennhanh.setText("Chuyển nhanh Napas 24/7");
        btnchuyennhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyennhanhActionPerformed(evt);
            }
        });

        btnchuyenthuong.setText("Chuyển thường");
        btnchuyenthuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyenthuongActionPerformed(evt);
            }
        });

        jLabel11.setText("Số tài khoản:");

        txtsotk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsotkActionPerformed(evt);
            }
        });

        jLabel12.setText("Tên người nhận:");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbnganhang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnchuyennhanh)
                        .addGap(117, 117, 117)
                        .addComponent(btnchuyenthuong))
                    .addComponent(jLabel5)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtsotk, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbnganhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnchuyennhanh)
                    .addComponent(btnchuyenthuong))
                .addGap(42, 42, 42)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtsotk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(276, 276, 276))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel14.setText("Số tiền:");

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btntimkiem.setText("Tìm kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        jLabel15.setText("Lời nhắn (nếu có):");

        txtloinhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloinhanActionPerformed(evt);
            }
        });

        tbDanhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số tài khoản", "Tên người nhận", "Số tiền", "Lời nhắn"
            }
        ));
        jScrollPane1.setViewportView(tbDanhsach);

        btnXuatExcel.setText("Xuất Excel");
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });

        jLabel1.setText("Thông tin chuyển khoản: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttien, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnXuatExcel)
                            .addGap(18, 18, 18)
                            .addComponent(btntimkiem)
                            .addGap(18, 18, 18)
                            .addComponent(btnluu)
                            .addGap(18, 18, 18)
                            .addComponent(btnsua)
                            .addGap(18, 18, 18)
                            .addComponent(btnxoa))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtloinhan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txttien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtloinhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnluu)
                    .addComponent(btntimkiem)
                    .addComponent(btnXuatExcel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin từ các trường
        String tenNganHang = (String) cbnganhang.getSelectedItem();
        String soTaiKhoan = txtsotk.getText();
        String tenNguoiNhan = txtname.getText();
        String loaiPhuongThuc = "=";
        if(btnchuyennhanh.isSelected()){
            loaiPhuongThuc = "Chuyển nhanh Napas 24/7";
        } else if(btnchuyenthuong.isSelected()){
            loaiPhuongThuc = "Chuyển thường";
        }
        String soTien = txttien.getText();
        String loiNhan = txtloinhan.getText();
        // Kiểm tra dữ liệu đầu vào
        if(soTaiKhoan.isEmpty() || tenNguoiNhan.isEmpty() || soTien.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        } else {
            // Kết nối database và thực hiện lưu
            try {
                Connection con = db.connect();
                String sql = "INSERT INTO GiaoDich (SoTaiKhoan, TenNguoiNhan, SoTien, LoaiChuyenTien, TuTaiKhoan, LoiNhan) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(0, tenNganHang);
                pst.setString(1, soTaiKhoan);
                pst.setString(2, tenNguoiNhan);
                pst.setString(3, soTien);
                pst.setString(4, loaiPhuongThuc);
                pst.setString(5, loiNhan);

                int result = pst.executeUpdate();
                if(result > 0) {
                    JOptionPane.showMessageDialog(this, "Lưu thông tin thành công!");
                }
                con.close();
            } catch(Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi lưu dữ liệu.");
            }
        }
    }//GEN-LAST:event_btnluuActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // Lấy dữ liệu từ các trường trong form
        String tenNganHang = (String) cbnganhang.getSelectedItem();
        String soTaiKhoan = txtsotk.getText();
        String tenNguoiNhan = txtname.getText();
        String loaiPhuongThuc = "=";
        if(btnchuyennhanh.isSelected()){
            loaiPhuongThuc = "Chuyển nhanh Napas 24/7";
        } else if(btnchuyenthuong.isSelected()){
            loaiPhuongThuc = "Chuyển thường";
        }
        String soTien = txttien.getText();
        String loiNhan = txtloinhan.getText();
        // Kiểm tra dữ liệu đầu vào
        if(soTaiKhoan.isEmpty() || tenNguoiNhan.isEmpty() || soTien.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        } else {
            // Kết nối cơ sở dữ liệu và thực hiện cập nhật
            try {
                Connection con = db.connect();
                String sql = "UPDATE GiaoDich SET TenNguoiNhan = ?, SoTien = ?, LoaiChuyenTien = ?, TuTaiKhoan = ?, LoiNhan = ? WHERE SoTaiKhoan = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(0, tenNganHang);
                pst.setString(1, soTaiKhoan);
                pst.setString(2, tenNguoiNhan);
                pst.setString(3, soTien);
                pst.setString(4, loaiPhuongThuc);
                pst.setString(5, loiNhan); // Điều kiện là số tài khoản

                int result = pst.executeUpdate();
                if(result > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy giao dịch với số tài khoản này.");
                }
                con.close();
            } catch(Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi cập nhật dữ liệu.");
            }
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        // Lấy số tài khoản từ form
        String soTaiKhoan = txtsotk.getText();

        // Kiểm tra dữ liệu đầu vào
        if(soTaiKhoan.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tài khoản để xóa giao dịch!");
        } else {
            // Hỏi xác nhận trước khi xóa
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa giao dịch này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

            if(confirm == JOptionPane.YES_OPTION) {
                // Kết nối cơ sở dữ liệu và thực hiện xóa
                try {
                    Connection con = db.connect();
                    String sql = "DELETE FROM GiaoDich WHERE SoTaiKhoan = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1, soTaiKhoan); // Điều kiện là số tài khoản

                    int result = pst.executeUpdate();
                    if(result > 0) {
                        JOptionPane.showMessageDialog(this, "Xóa giao dịch thành công!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Không tìm thấy giao dịch với số tài khoản này.");
                    }
                    con.close();
                } catch(Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi xóa giao dịch.");
                }
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        // Lấy số tài khoản từ form
        String soTaiKhoan = txtsotk.getText();

        // Kiểm tra xem người dùng đã nhập số tài khoản chưa
        if(soTaiKhoan.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tài khoản để xóa giao dịch!");
        } else {
            // Kết nối cơ sở dữ liệu và tìm kiếm thông tin
            try {
                Connection con = db.connect();
                String sql = "SELECT * FROM GiaoDich WHERE SoTaiKhoan = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, soTaiKhoan); // Điều kiện là số tài khoản

                ResultSet rs = pst.executeQuery();
                if(rs.next()) {
                    // Hiển thị thông tin giao dịch nếu tìm thấy
                    String tenNguoiNhan = rs.getString("TenNguoiNhan");
                    String soTien = rs.getString("SoTien");
                    String loaiPhuongThuc = rs.getString("LoaiPhuongThuc");
                    String tuTaiKhoan = rs.getString("TuTaiKhoan");
                    String loiNhan = rs.getString("LoiNhan");

                    // Gán các giá trị tìm thấy vào form
                    txtname.setText(tenNguoiNhan);
                    txttien.setText(soTien);
                    if(loaiPhuongThuc.equals("Chuyển nhanh Napas 24/7")) {
                        btnchuyennhanh.setSelected(true);
                    } else if(loaiPhuongThuc.equals("Chuyển thường")) {
                        btnchuyenthuong.setSelected(true);
                    }
                    txtloinhan.setText(loiNhan);
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy giao dịch với số tài khoản này.");
                }
                con.close();
            } catch(Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi tìm kiếm dữ liệu.");
            }
        }
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void cbnganhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnganhangActionPerformed
        // TODO add your handling code here:                             
        // Lấy ngân hàng đã chọn từ JComboBox
        String selectedBank = (String) cbnganhang.getSelectedItem();

        // Thực hiện các hành động tùy thuộc vào ngân hàng được chọn
        switch (selectedBank) {
            case "Vietcombank (Ngân hàng TMCP Ngoại Thương Việt Nam)":
                // Thực hiện hành động cho Vietcombank
                System.out.println("Bạn đã chọn Vietcombank.");
                break;
            case "BIDV (Ngân hàng Đầu tư và phát triển Việt Nam)":
                // Thực hiện hành động cho BIDV
                System.out.println("Bạn đã chọn BIDV.");
                break;
            case "Techcombank (Ngân hàng Kỹ thương Việt Nam)":
                // Thực hiện hành động cho Techcombank
                System.out.println("Bạn đã chọn Techcombank.");
                break;
            case "TP Bank (Ngân hàng tiên phong)":
                // Thực hiện hành động cho TP Bank
                System.out.println("Bạn đã chọn TP Bank.");
                break;
            case "MB Bank (Ngân hàng Quân đội Việt Nam)":
                // Thực hiện hành động cho MB Bank
                System.out.println("Bạn đã chọn MB Bank.");
                break;
            default:
                System.out.println("Ngân hàng không xác định.");
                break;
        }
    }//GEN-LAST:event_cbnganhangActionPerformed

    private void txtsotkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsotkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsotkActionPerformed

    private void txtloinhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloinhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloinhanActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed
    private static CellStyle DinhdangHeader(XSSFSheet sheet) {
        // Tạo font
        XSSFFont font = sheet.getWorkbook().createFont();
        font.setFontName("Times New Roman");
        font.setBold(true);
        font.setFontHeightInPoints((short) 12); // Kích thước font
        font.setColor(IndexedColors.WHITE.getIndex()); // Màu chữ

        // Tạo CellStyle
        CellStyle cellStyle = sheet.getWorkbook().createCellStyle();
        cellStyle.setFont(font);
        cellStyle.setAlignment(HorizontalAlignment.CENTER);
        cellStyle.setVerticalAlignment(VerticalAlignment.TOP);
        cellStyle.setFillForegroundColor(IndexedColors.DARK_GREEN.getIndex());
        cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        cellStyle.setBorderBottom(BorderStyle.THIN);
        cellStyle.setWrapText(true);
        return cellStyle;
    }

    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        // TODO add your handling code here:
        try {
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet spreadsheet = workbook.createSheet("Danh sách chuyển tiền");

        // Tiêu đề bảng
        CreationHelper createHelper = workbook.getCreationHelper();
        XSSFRow row = spreadsheet.createRow(0);
        row.setHeight((short) 500);
        Cell cell = row.createCell(0, CellType.STRING);
        cell.setCellValue("DANH SÁCH CHUYỂN TIỀN");

        // Tạo dòng tiêu đề cho bảng
        CellStyle cellStyle_Head = DinhdangHeader(spreadsheet);
        row = spreadsheet.createRow(1);
        row.setHeight((short) 500);

        String[] headers = {"Số tài khoản", "Tên người nhận", "Số tiền", "Lời nhắn"};
        for (int j = 0; j < headers.length; j++) {
            cell = row.createCell(j);
            cell.setCellStyle(cellStyle_Head);
            cell.setCellValue(headers[j]);
        }

        // Kết nối DB
        Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\NguyenDinhTam:1433;databaseName=Embeiu", "sa", "27012004");
        String sql = "SELECT so_tai_khoan, ten_nguoi_nhan, so_tien, loi_nhan FROM khoan_vay"; // Cập nhật câu truy vấn để chọn các cột phù hợp
        PreparedStatement st = con.prepareStatement(sql);
        ResultSet rs = st.executeQuery();

        // Định dạng ô chứa dữ liệu
        CellStyle cellStyle_data = workbook.createCellStyle();
        cellStyle_data.setBorderLeft(BorderStyle.THIN);
        cellStyle_data.setBorderRight(BorderStyle.THIN);
        cellStyle_data.setBorderBottom(BorderStyle.THIN);

        int rowIndex = 2; // Bắt đầu từ dòng 2 vì dòng 0 và 1 đã sử dụng
        while (rs.next()) {
            row = spreadsheet.createRow(rowIndex);
            row.setHeight((short) 400);

            cell = row.createCell(0);
            cell.setCellStyle(cellStyle_data);
            cell.setCellValue(rs.getString("so_tai_khoan"));

            cell = row.createCell(1);
            cell.setCellStyle(cellStyle_data);
            cell.setCellValue(rs.getString("ten_nguoi_nhan"));

            cell = row.createCell(2);
            cell.setCellStyle(cellStyle_data);
            cell.setCellValue(rs.getDouble("so_tien")); // Giả sử so_tien là kiểu số

            cell = row.createCell(3);
            cell.setCellStyle(cellStyle_data);
            cell.setCellValue(rs.getString("loi_nhan"));

            rowIndex++;
        }

        // Ghi dữ liệu vào file
        FileOutputStream out = new FileOutputStream(new File("DanhSachChuyenTien.xlsx"));
        workbook.write(out);
        out.close();
        workbook.close();
        
        System.out.println("Excel file created successfully!");
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnXuatExcelActionPerformed

    private void btnchuyenthuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyenthuongActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin từ các trường nhập liệu
    String soTaiKhoan = txtsotk.getText();
    String tenNguoiNhan = txtname.getText();
    String soTien = txttien.getText();
    String loiNhan = txtloinhan.getText();
    
    // Kiểm tra xem các trường có trống không
    if (soTaiKhoan.isEmpty() || tenNguoiNhan.isEmpty() || soTien.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Xử lý logic chuyển thường
    try {
        // Kết nối đến cơ sở dữ liệu
        Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\NguyenDinhTam:1433;databaseName=Embeiu", "sa", "27012004");
        String sql = "INSERT INTO chuyen_tien (so_tai_khoan, ten_nguoi_nhan, so_tien, phuong_thuc, loi_nhan) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, soTaiKhoan);
        pst.setString(2, tenNguoiNhan);
        pst.setDouble(3, Double.parseDouble(soTien));
        pst.setString(4, "Chuyển thường"); // Phương thức chuyển
        pst.setString(5, loiNhan);
        
        int rowsAffected = pst.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Chuyển tiền thường thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Chuyển tiền thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        
        // Đóng kết nối
        pst.close();
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnchuyenthuongActionPerformed

    private void btnchuyennhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyennhanhActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin từ các trường nhập liệu
    String soTaiKhoan = txtsotk.getText();
    String tenNguoiNhan = txtname.getText();
    String soTien = txttien.getText();
    String loiNhan = txtloinhan.getText();
    
    // Kiểm tra xem các trường có trống không
    if (soTaiKhoan.isEmpty() || tenNguoiNhan.isEmpty() || soTien.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Xử lý logic chuyển nhanh
    try {
        // Kết nối đến cơ sở dữ liệu
        Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\NguyenDinhTam:1433;databaseName=Embeiu", "sa", "27012004");
        String sql = "INSERT INTO chuyen_tien (so_tai_khoan, ten_nguoi_nhan, so_tien, phuong_thuc, loi_nhan) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, soTaiKhoan);
        pst.setString(2, tenNguoiNhan);
        pst.setDouble(3, Double.parseDouble(soTien));
        pst.setString(4, "Chuyển nhanh Napas 24/7"); // Phương thức chuyển
        pst.setString(5, loiNhan);
        
        int rowsAffected = pst.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Chuyển tiền nhanh thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Chuyển tiền thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        
        // Đóng kết nối
        pst.close();
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnchuyennhanhActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JRadioButton btnchuyennhanh;
    private javax.swing.JRadioButton btnchuyenthuong;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbnganhang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDanhsach;
    private javax.swing.JTextField txtloinhan;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsotk;
    private javax.swing.JTextField txttien;
    // End of variables declaration//GEN-END:variables
}
