/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.controllers.user;

<<<<<<< HEAD
//import com.mycompany.controllers.admin.quanlynguoidung;
=======
import com.mycompany.controllers.user.GiaoDich;
import com.mycompany.db;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
>>>>>>> 3c2de14a14f89fd0933321eb7d0fbae5ac7fca34
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class quanligiaodichcanhan extends javax.swing.JFrame {

    /**
     * Creates new form quanligiaodichcanhan
     */
    public quanligiaodichcanhan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nguoi_dung1 = new javax.swing.JLabel();
        nguoi_dung2 = new javax.swing.JLabel();
        nguoi_dung3 = new javax.swing.JLabel();
        nguoi_dung4 = new javax.swing.JLabel();
        nguoi_dung5 = new javax.swing.JLabel();
        nguoi_dung6 = new javax.swing.JLabel();
        nguoi_dung7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txttien = new javax.swing.JTextField();
        btnluu = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btntimkiem = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtloinhan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtsodu = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbnganhang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnchuyennhanh = new javax.swing.JRadioButton();
        btnchuyenthuong = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtsotk = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nguoi_dung1.setBackground(java.awt.Color.white);
        nguoi_dung1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nguoi_dung1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nguoi_dung1.setText("  Người dùng");
        nguoi_dung1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nguoi_dung1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nguoi_dung1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nguoi_dung1MouseClicked(evt);
            }
        });

        nguoi_dung2.setBackground(java.awt.Color.white);
        nguoi_dung2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nguoi_dung2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nguoi_dung2.setText("Giao dịch");
        nguoi_dung2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nguoi_dung2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nguoi_dung2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nguoi_dung2MouseClicked(evt);
            }
        });

        nguoi_dung3.setBackground(java.awt.Color.white);
        nguoi_dung3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nguoi_dung3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nguoi_dung3.setText("Tiết kiệm");
        nguoi_dung3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nguoi_dung3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nguoi_dung3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nguoi_dung3MouseClicked(evt);
            }
        });

        nguoi_dung4.setBackground(java.awt.Color.white);
        nguoi_dung4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nguoi_dung4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nguoi_dung4.setText("Vay vốn");
        nguoi_dung4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nguoi_dung4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nguoi_dung4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nguoi_dung4MouseClicked(evt);
            }
        });

        nguoi_dung5.setBackground(java.awt.Color.white);
        nguoi_dung5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nguoi_dung5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nguoi_dung5.setText("Trả nợ");
        nguoi_dung5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nguoi_dung5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nguoi_dung5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nguoi_dung5MouseClicked(evt);
            }
        });

        nguoi_dung6.setBackground(java.awt.Color.white);
        nguoi_dung6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nguoi_dung6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nguoi_dung6.setText("Yêu cầu hỗ trợ");
        nguoi_dung6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nguoi_dung6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nguoi_dung6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nguoi_dung6MouseClicked(evt);
            }
        });

        nguoi_dung7.setBackground(java.awt.Color.white);
        nguoi_dung7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nguoi_dung7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nguoi_dung7.setText("Thẻ cá nhân");
        nguoi_dung7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nguoi_dung7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nguoi_dung7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nguoi_dung7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nguoi_dung1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nguoi_dung2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nguoi_dung3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nguoi_dung4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nguoi_dung5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nguoi_dung6, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(nguoi_dung7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nguoi_dung1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nguoi_dung2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nguoi_dung3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nguoi_dung4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nguoi_dung5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nguoi_dung6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nguoi_dung7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setForeground(new java.awt.Color(255, 0, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quản lí giao dịch cá nhân");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(167, 167, 167))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel13.setText("Từ:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tài khoản chính", "Tài khoản tiết kiệm" }));
        jComboBox2.setToolTipText("");

        jLabel14.setText("Số tiền:");

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btntimkiem.setText("Tìm kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        jLabel15.setText("Lời nhắn (nếu có):");

        jLabel16.setText("Số dư: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 277, Short.MAX_VALUE)
                        .addComponent(btntimkiem)
                        .addGap(18, 18, 18)
                        .addComponent(btnluu)
                        .addGap(18, 18, 18)
                        .addComponent(btnsua)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtloinhan))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, 357, Short.MAX_VALUE)
                                    .addComponent(txttien))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsodu)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txttien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtloinhan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnluu)
                    .addComponent(btntimkiem))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Ngân hàng thụ hưởng:");

        cbnganhang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vietcombank (Ngân hàng TMCP Ngoại Thương Việt Nam)", "BIDV (Ngân hàng Đầu tư và phát triển Việt Nam)", "Techcombank (Ngân hàng Kỹ thương Việt Nam)", "TP Bank (Ngân hàng tiên phong)", "MB Bank (Ngân hàng Quân đội Việt Nam)" }));
        cbnganhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnganhangActionPerformed(evt);
            }
        });

        jLabel5.setText("Loại phương thức chuyển tiền:");

        btnchuyennhanh.setText("Chuyển nhanh Napas 24/7");
        btnchuyennhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyennhanhActionPerformed(evt);
            }
        });

        btnchuyenthuong.setText("Chuyển thường");

        jLabel11.setText("Số tài khoản:");

        jLabel12.setText("Tên người nhận:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbnganhang, 0, 502, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnchuyennhanh)
                                .addGap(117, 117, 117)
                                .addComponent(btnchuyenthuong))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addComponent(txtsotk)))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbnganhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnchuyennhanh)
                    .addComponent(btnchuyenthuong))
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtsotk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nguoi_dung1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nguoi_dung1MouseClicked
<<<<<<< HEAD
//        quanlynguoidung qlnd = new quanlynguoidung();
//        qlnd.setVisible(true);
//        this.dispose();
//        JOptionPane.showMessageDialog(qlnd, "ok");
=======

>>>>>>> 3c2de14a14f89fd0933321eb7d0fbae5ac7fca34
    }//GEN-LAST:event_nguoi_dung1MouseClicked

    private void nguoi_dung2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nguoi_dung2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nguoi_dung2MouseClicked

    private void nguoi_dung3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nguoi_dung3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nguoi_dung3MouseClicked

    private void nguoi_dung4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nguoi_dung4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nguoi_dung4MouseClicked

    private void nguoi_dung5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nguoi_dung5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nguoi_dung5MouseClicked

    private void nguoi_dung6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nguoi_dung6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nguoi_dung6MouseClicked

    private void nguoi_dung7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nguoi_dung7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nguoi_dung7MouseClicked

    private void btnchuyennhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyennhanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchuyennhanhActionPerformed
private void loadGiaoDich() {
    try {
        Connection con = db.connect(); // Kết nối tới cơ sở dữ liệu
        String sql = "SELECT * FROM GiaoDich"; // Câu lệnh SQL để chọn tất cả giao dịch
        Statement st =con.createStatement();
        ResultSet rs = st.executeQuery(sql); // Thực thi truy vấn

        // Đặt tiêu đề cho bảng
        String[] tieude = {"Số tài khoản", "Tên người nhận", "Loại giao dịch", "Số tiền", "Ngày giao dịch"};
        DefaultTableModel tb = new DefaultTableModel(tieude, 0);

        // Lặp qua các kết quả trả về
        while (rs.next()) {
            Vector v = new Vector();
            v.add(rs.getString("tennganhang"));
            v.add(rs.getString("SoTaiKhoan")); // Số tài khoản
            v.add(rs.getString("TenNguoiNhan")); // Tên người nhận
            v.add(rs.getString("Loaiphuongthuc")); // Loại giao dịch
            v.add(rs.getString("SoTien")); // Số tiền
            v.add(rs.getString("Loinhan")); // Ngày giao dịch
            v.add(rs.getString("Sodu"));
        }

        con.close(); // Đóng kết nối
    } catch (Exception e) {
        e.printStackTrace(); // In ra lỗi nếu có
    }


}
    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin từ các trường
   
       
    String tenNganHang = (String) cbnganhang.getSelectedItem();
    String soTaiKhoan = txtsotk.getText();
    String tenNguoiNhan = txtname.getText();
    String loaiPhuongThuc = "=";
    if(btnchuyennhanh.isSelected()){
    loaiPhuongThuc = "Chuyển nhanh Napas 24/7";
} else if(btnchuyenthuong.isSelected()){
    loaiPhuongThuc = "Chuyển thường";
}
    String tuTaiKhoan = (String) jComboBox2.getSelectedItem();
    String soTien = txttien.getText();
    String loiNhan = txtloinhan.getText();
    String soDu = txtsodu.getText();
// Kiểm tra dữ liệu đầu vào
if(soTaiKhoan.isEmpty() || tenNguoiNhan.isEmpty() || soTien.isEmpty()){
    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
} else {
    // Kết nối database và thực hiện lưu
    try {
        Connection con = db.connect();
        String sql = "INSERT INTO GiaoDich (SoTaiKhoan, TenNguoiNhan, SoTien, LoaiChuyenTien, TuTaiKhoan, LoiNhan) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(0, tenNganHang);
        pst.setString(1, soTaiKhoan);
        pst.setString(2, tenNguoiNhan);
        pst.setString(3, soTien);
        pst.setString(4, loaiPhuongThuc);
        pst.setString(5, tuTaiKhoan);
        pst.setString(6, loiNhan);
        
        int result = pst.executeUpdate();
        if(result > 0) {
            JOptionPane.showMessageDialog(this, "Lưu thông tin thành công!");
        }
        con.close();
    } catch(Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi lưu dữ liệu.");
    }
}

   
    }//GEN-LAST:event_btnluuActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
// Lấy dữ liệu từ các trường trong form
    String tenNganHang = (String) cbnganhang.getSelectedItem();
    String soTaiKhoan = txtsotk.getText();
    String tenNguoiNhan = txtname.getText();
    String loaiPhuongThuc = "=";
     if(btnchuyennhanh.isSelected()){
    loaiPhuongThuc = "Chuyển nhanh Napas 24/7";
} else if(btnchuyenthuong.isSelected()){
    loaiPhuongThuc = "Chuyển thường";
}
String tuTaiKhoan = (String) jComboBox2.getSelectedItem();
    String soTien = txttien.getText();
    String loiNhan = txtloinhan.getText();
    String soDu = txtsodu.getText();
// Kiểm tra dữ liệu đầu vào
if(soTaiKhoan.isEmpty() || tenNguoiNhan.isEmpty() || soTien.isEmpty()){
    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
} else {
    // Kết nối cơ sở dữ liệu và thực hiện cập nhật
    try {
        Connection con = db.connect();
        String sql = "UPDATE GiaoDich SET TenNguoiNhan = ?, SoTien = ?, LoaiChuyenTien = ?, TuTaiKhoan = ?, LoiNhan = ? WHERE SoTaiKhoan = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(0, tenNganHang);
        pst.setString(1, soTaiKhoan);
        pst.setString(2, tenNguoiNhan);
        pst.setString(3, soTien);
        pst.setString(4, loaiPhuongThuc);
        pst.setString(5, tuTaiKhoan);
        pst.setString(6, loiNhan); // Điều kiện là số tài khoản
        
        int result = pst.executeUpdate();
        if(result > 0) {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy giao dịch với số tài khoản này.");
        }
        con.close();
    } catch(Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi cập nhật dữ liệu.");
    }
}

    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        // Lấy số tài khoản từ form
 String soTaiKhoan = txtsotk.getText();

// Kiểm tra dữ liệu đầu vào
if(soTaiKhoan.isEmpty()){
    JOptionPane.showMessageDialog(this, "Vui lòng nhập số tài khoản để xóa giao dịch!");
} else {
    // Hỏi xác nhận trước khi xóa
    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa giao dịch này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
    
    if(confirm == JOptionPane.YES_OPTION) {
        // Kết nối cơ sở dữ liệu và thực hiện xóa
        try {
            Connection con = db.connect();
            String sql = "DELETE FROM GiaoDich WHERE SoTaiKhoan = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, soTaiKhoan); // Điều kiện là số tài khoản
            
            int result = pst.executeUpdate();
            if(result > 0) {
                JOptionPane.showMessageDialog(this, "Xóa giao dịch thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy giao dịch với số tài khoản này.");
            }
            con.close();
        } catch(Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi xóa giao dịch.");
        }
    }
}

    }//GEN-LAST:event_btnxoaActionPerformed

    private void cbnganhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnganhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnganhangActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        // Lấy số tài khoản từ form
String soTaiKhoan = txtsotk.getText();

// Kiểm tra xem người dùng đã nhập số tài khoản chưa
if(soTaiKhoan.isEmpty()){
    JOptionPane.showMessageDialog(this, "Vui lòng nhập số tài khoản để xóa giao dịch!");
} else {
    // Kết nối cơ sở dữ liệu và tìm kiếm thông tin
    try {
        Connection con = db.connect();
        String sql = "SELECT * FROM GiaoDich WHERE SoTaiKhoan = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, soTaiKhoan); // Điều kiện là số tài khoản
        
        ResultSet rs = pst.executeQuery();
        if(rs.next()) {
            // Hiển thị thông tin giao dịch nếu tìm thấy
            String tenNguoiNhan = rs.getString("TenNguoiNhan");
            String soTien = rs.getString("SoTien");
            String loaiPhuongThuc = rs.getString("LoaiPhuongThuc");
            String tuTaiKhoan = rs.getString("TuTaiKhoan");
            String loiNhan = rs.getString("LoiNhan");
            
            // Gán các giá trị tìm thấy vào form
            txtname.setText(tenNguoiNhan);
            txttien.setText(soTien);
            if(loaiPhuongThuc.equals("Chuyển nhanh Napas 24/7")) {
                btnchuyennhanh.setSelected(true);
            } else if(loaiPhuongThuc.equals("Chuyển thường")) {
                btnchuyenthuong.setSelected(true);
            }
            jComboBox2.setSelectedItem(tuTaiKhoan);
            txtloinhan.setText(loiNhan);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy giao dịch với số tài khoản này.");
        }
        con.close();
    } catch(Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi tìm kiếm dữ liệu.");
    }
}

    }//GEN-LAST:event_btntimkiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanligiaodichcanhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanligiaodichcanhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanligiaodichcanhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanligiaodichcanhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanligiaodichcanhan().setVisible(true);
            }
        });
    }
private void luuGiaoDichVaoDatabase(GiaoDich giaoDich) {
    try {
        // Tạo kết nối với cơ sở dữ liệu
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydatabase", "username", "password");

        // Tạo câu lệnh SQL để thêm giao dịch
        String sql = "INSERT INTO GiaoDich (tenNganHang, soTaiKhoan, tenNguoiNhan, loaiPhuongThuc, tuTaiKhoan, soTien, loiNhan, soDu) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);

        // Thiết lập các tham số
        ps.setString(1, giaoDich.getTenNganHang());
        ps.setString(2, giaoDich.getSoTaiKhoan());
        ps.setString(3, giaoDich.getTenNguoiNhan());
        ps.setString(4, giaoDich.getLoaiPhuongThuc());
        ps.setString(5, giaoDich.getTuTaiKhoan());
        ps.setString(6, giaoDich.getSoTien());
        ps.setString(7, giaoDich.getLoiNhan());
        ps.setString(8, giaoDich.getSoDu());

        // Thực thi câu lệnh
        ps.executeUpdate();

        // Đóng kết nối
        ps.close();
        conn.close();

        System.out.println("Giao dịch đã được lưu");
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnchuyennhanh;
    private javax.swing.JRadioButton btnchuyenthuong;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbnganhang;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nguoi_dung1;
    private javax.swing.JLabel nguoi_dung2;
    private javax.swing.JLabel nguoi_dung3;
    private javax.swing.JLabel nguoi_dung4;
    private javax.swing.JLabel nguoi_dung5;
    private javax.swing.JLabel nguoi_dung6;
    private javax.swing.JLabel nguoi_dung7;
    private javax.swing.JTextField txtloinhan;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsodu;
    private javax.swing.JTextField txtsotk;
    private javax.swing.JTextField txttien;
    // End of variables declaration//GEN-END:variables
}
